version: 0.1

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws s3 sync . s3://rentaportablesink.com
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - *
  discard-paths: no
